version: '3.8'
services:
  frontend:
    container_name: frontend
    build: ./frontend
    volumes:
      - './:/app'
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start

  backend:
    build:
      context: ./backend
    volumes:
      - /home/caio/Área de Trabalho/SisOpFinanc/project/backend
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - ./backend/.env
 
  db:
    image: postgres:latest
    env_file:
      - ./backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    command: redis-server
    volumes:
      - redis_data:/data

volumes:
  postgres_data: {}
  redis_data: {}
